### PR TITLE
Switch express.io with express.oi

### PR DESCRIPTION
**Pull request by mirzahusadzic**
PR created for an [isssue](https://github.com/mapic/mapic/issues/19).

### CODE REVIEW

**Comment by knutole** [comment]
Great, thank you @mirzahusadzic !

**Comment by knutole** [comment]
Add yourself to list of contribs in README if you like 👍

**Comment by mirzahusadzic** [comment]
@knutole Thanks, I appreciate it 👍

Could you please apply it via [patch](https://github.com/mapic/engine/files/893191/add-myself-to-the-list-of.txt) .

**Comment by knutole** [comment]
I prefer you just create a PR, or include it in next PR if you have more contribs! 🥇

**Pull request merged**
